package com.raffaelcavaliere.setlists.chordpro;

public enum DirectiveElementType {
    CHORDPRO_TITLE,
    CHORDPRO_SUBTITLE,
    CHORDPRO_COMPOSER,
    CHORDPRO_LYRICIST,
    CHORDPRO_ARRANGER,
    CHORDPRO_ALBUM,
    CHORDPRO_COPYRIGHT,
    CHORDPRO_YEAR,
    CHORDPRO_KEY,
    CHORDPRO_TIME,
    CHORDPRO_TEMPO,
    CHORDPRO_DURATION,
    CHORDPRO_DEFINE,
    CHORDPRO_COMMENT,
    CHORDPRO_COMMENT_ITALIC,
    CHORDPRO_COMMENT_BOX
}
