package com.raffaelcavaliere.setlists.chordpro;

public enum TokenType {
  CHORDPRO_NEWLINE_TOKEN,
  CHORDPRO_SQUARE_BRACKET_LEFT,
  CHORDPRO_SQUARE_BRACKET_RIGHT,
  CHORDPRO_CHORD_TOKEN,
  CHORDPRO_CURLY_BRACKET_LEFT,
  CHORDPRO_CURLY_BRACKET_RIGHT,
  CHORDPRO_TAG_DELIMITER,
  CHORDPRO_TAG_KEY_TOKEN,
  CHORDPRO_TAG_VALUE_TOKEN,
  CHORDPRO_TEXT_TOKEN
}
